/* Configurações primordiais da SALA */

let room = HBInit({
    roomName: 'Teste',
    maxPlayers: 16,
    playerName: 'Bot',
    noPlayer: true,
    public: false
});

/* variáveis Globais */

const role = { PLAYER: 0, ADMIN: 1, MASTER: 2 };
const uniform = { COUNTRY: 0, CLUBLA: 1, CLUBEU: 2 };
const speedCoefficient = 100 / (5 * (0.99 ** 60 + 1));
const announcementColor = 0xfffafa;
let point = [{ x: 0, y: 0 },{ x: 0, y: 0 }];
let ballSpeed;
let lastPlayerKick = { id: 0, team: 0 };
let penultPlayerKick;
let undefeatedScore = 0;
let players;
let numberEachTeam;

/* variáveis dos times */

let nameHome = 'Mandante';
let acronymHome = 'Home';
let nameGuest = 'Visitante';
let acronymGuest = 'Away';
let emojihome = '🏠';
let emojiGuest = '✈️';
let playersTeamHome;
let playersTeamGuest;
let playersTeamSpec;
let goalsHome = [];
let goalsGuest = [];
let Hposs;
let Gposs;

/* Lista de comandos */

let commands = {
    "ajuda": {
        "similar": ["help"],
        "roles": role.PLAYER,
        "desc": `Este comando mostra todos os outros comandos disponíveis`,
        "function": helpCommand,
    },
    "quit": {
        "similar": ["quitar", "leave", "sair", "qt"],
        "roles": role.PLAYER,
        "desc": `Este comando te desconecta da sala.`,
        "function": leaveCommmand,
    },
    "uniforme": {
        "similar": ["uni", "uniformes", "uniform"],
        "roles": role.PLAYER,
        "desc": `Este comando mostra todos os uniformes disponíveis para seu time vestir.`,
        "function": uniformCommand,
    },
    "reserva": {
        "similar": ["sub"],
        "roles": role.PLAYER,
        "desc": `Este comando muda o uniforme de seu time para o uniforme reserva disponível.`,
        "function": reserveCommand,
    },
    "time": {
        "similar": ["team", "tm"],
        "roles": role.ADMIN,
        "desc": `Este comando define os times da sala.`,
        "function": teamCommand,
    },
    "restart": {
        "similar": ["rr", "res"],
        "roles": role.ADMIN,
        "desc": `Este comando reinicia a partida.`,
        "function": restartCommand,
    },
    "admin": {
        "similar": ["adm"],
        "roles": role.ADMIN,
        "desc": `Este comando concede ADMIN para outro player`,
        "function": adminCommand,
    },
}

/* Lista de uniformes */

let uniformes = {

    /* Times brasileiros */
    
    "cor": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "san": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "mir": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "pal": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "sp": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "fla": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "vas": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "bot": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "flu": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "cru": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "galo": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "inter": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "grem": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "bah": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "vit": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "riv": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "boca": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "cdl": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },

    /* Times gringos */

    "psg": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "bay": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "bor": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "chel": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "liv": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "ars": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "juve": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "itm": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "nap": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "acm": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "rma": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "fcb": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "val": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
    "rb": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },

    /* Times custom */

    "reggae": {
        "name":   x,
        "type": Uniform.COUNTRY,
        "emoji":   x,
        "angle":   x,
        "textcolor":   x,
        "color1":   x,
        "color2":   x, 
        "color3":   x,
        "angle2":   x,
        "textcolor2":   x,
        "color21":   x,
        "color22":   x,
        "color23":   x,
    },
}

/* Configurações principais da SALA */

room.setDefaultStadium('Big');
room.setScoreLimit(0);
room.setTimeLimit(3);
room.setTeamsLock(true);

/* Configurações de PLAYERS */

function updateAdmins() {
    let players = room.getPlayerList();
    if (players.length == 0) return;
    if (players.find((player) => player.admin) != null) return;
    room.setPlayerAdmin(players[0].id, true);
}

room.onPlayerJoin = function (player) {
    updateAdmins();
};

room.onPlayerLeave = function (player) {
    updateAdmins();
};
